#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : deprecated-typing
Version  : 3.6.6
Release  : 26
URL      : https://files.pythonhosted.org/packages/bf/9b/2bf84e841575b633d8d91ad923e198a415e3901f228715524689495b4317/typing-3.6.6.tar.gz
Source0  : https://files.pythonhosted.org/packages/bf/9b/2bf84e841575b633d8d91ad923e198a415e3901f228715524689495b4317/typing-3.6.6.tar.gz
Summary  : Type Hints for Python
Group    : Development/Tools
License  : Python-2.0
Requires: deprecated-typing-license = %{version}-%{release}
Requires: deprecated-typing-python = %{version}-%{release}
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3

%description
===================
PEP 484: Type Hints
===================
.. image:: https://badges.gitter.im/python/typing.svg
:alt: Chat at https://gitter.im/python/typing
:target: https://gitter.im/python/typing?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

%package legacypython
Summary: legacypython components for the deprecated-typing package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the deprecated-typing package.


%package license
Summary: license components for the deprecated-typing package.
Group: Default

%description license
license components for the deprecated-typing package.


%package python
Summary: python components for the deprecated-typing package.
Group: Default

%description python
python components for the deprecated-typing package.


%prep
%setup -q -n typing-3.6.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554329558
export MAKEFLAGS=%{?_smp_mflags}
python2 setup.py build -b py2

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/deprecated-typing
cp LICENSE %{buildroot}/usr/share/package-licenses/deprecated-typing/LICENSE
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/deprecated-typing/LICENSE

%files python
%defattr(-,root,root,-)
